window.META_PLAYERS = [
  // =====================================================
  // DELANTEROS
  // =====================================================

  {
    id: "lois-openda",
    nombre: "Loïs Openda",
    ovr: 80,
    posicionPrincipal: "ST",
    posiciones: ["ST", "CAM"],
    categoria: "DEL",
    prioridadMeta: 3,
    perfil: "Delantero de muchísimo ritmo y gran perfil starter.",
    tags: ["Pace", "Starter", "ST", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "ademola-lookman",
    nombre: "Ademola Lookman",
    ovr: 83,
    posicionPrincipal: "ST",
    posiciones: ["ST", "CAM", "LM", "LW"],
    categoria: "DEL",
    prioridadMeta: 3,
    perfil: "Atacante muy versátil, rápido y usable en varias posiciones.",
    tags: ["Versátil", "Starter", "Pace", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "racheal-kundananji",
    nombre: "Racheal Kundananji",
    ovr: 81,
    posicionPrincipal: "ST",
    posiciones: ["ST", "LM", "LW", "CAM"],
    categoria: "DEL",
    prioridadMeta: 3,
    perfil: "Muchísimo ritmo, físico fuerte y muy buen perfil ofensivo.",
    tags: ["Pace", "Physical", "Starter", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "inaki-williams",
    nombre: "Iñaki Williams",
    ovr: null,
    posicionPrincipal: "ST",
    posiciones: ["ST", "RW", "RM"],
    categoria: "DEL",
    prioridadMeta: 3,
    perfil: "Atacante rápido, alto y muy útil para equipos starter.",
    tags: ["Pace", "Starter", "Lengthy", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "benjamin-sesko",
    nombre: "Benjamin Šeško",
    ovr: null,
    posicionPrincipal: "ST",
    posiciones: ["ST"],
    categoria: "DEL",
    prioridadMeta: 2,
    perfil: "Delantero alto con gran velocidad y buen remate.",
    tags: ["Tall", "Pace", "Starter"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "federico-chiesa",
    nombre: "Federico Chiesa",
    ovr: null,
    posicionPrincipal: "ST",
    posiciones: ["ST", "RW", "LW"],
    categoria: "DEL",
    prioridadMeta: 2,
    perfil: "Explosivo, rápido y flexible en ataque.",
    tags: ["Pace", "Explosive", "Versátil"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "bryan-mbeumo",
    nombre: "Bryan Mbeumo",
    ovr: null,
    posicionPrincipal: "ST",
    posiciones: ["ST", "CAM", "RW"],
    categoria: "DEL",
    prioridadMeta: 2,
    perfil: "Buen ritmo, definición y varias posiciones ofensivas.",
    tags: ["Pace", "Finishing", "Versátil"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "donyell-malen",
    nombre: "Donyell Malen",
    ovr: 83,
    posicionPrincipal: "ST",
    posiciones: ["ST"],
    categoria: "DEL",
    prioridadMeta: 2,
    perfil: "Delantero equilibrado con ritmo, tiro y regate.",
    tags: ["Pace", "Dribbling", "Starter"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "omar-marmoush",
    nombre: "Omar Marmoush",
    ovr: null,
    posicionPrincipal: "ST",
    posiciones: ["ST", "LW", "CAM"],
    categoria: "DEL",
    prioridadMeta: 2,
    perfil: "Atacante rápido con buen tiro y varias posiciones.",
    tags: ["Pace", "Versátil", "Starter"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  // =====================================================
  // EXTREMOS
  // =====================================================

  {
    id: "anthony-elanga",
    nombre: "Anthony Elanga",
    ovr: 79,
    posicionPrincipal: "RW",
    posiciones: ["RW", "RM"],
    categoria: "EXT",
    prioridadMeta: 3,
    perfil: "Extremo rapidísimo. Ya comprobamos demanda real en mercado.",
    tags: ["Pace", "Premier", "Starter", "Trade"],
    precioMercado: 1800,
    compraIdealMin: 1150,
    compraIdealMax: 1300,
    compraMaxima: 1400,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "yankuba-minteh",
    nombre: "Yankuba Minteh",
    ovr: 80,
    posicionPrincipal: "RW",
    posiciones: ["RW", "LW", "RM", "LM"],
    categoria: "EXT",
    prioridadMeta: 3,
    perfil: "Muchísimo ritmo y cuatro posiciones de banda.",
    tags: ["Pace", "Premier", "Versátil", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "pedro-neto",
    nombre: "Pedro Neto",
    ovr: null,
    posicionPrincipal: "RW",
    posiciones: ["RW", "LW", "RM", "LM"],
    categoria: "EXT",
    prioridadMeta: 3,
    perfil: "Extremo explosivo, rápido y muy versátil.",
    tags: ["Pace", "Premier", "Versátil", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "moussa-diaby",
    nombre: "Moussa Diaby",
    ovr: null,
    posicionPrincipal: "RW",
    posiciones: ["RW", "LW"],
    categoria: "EXT",
    prioridadMeta: 3,
    perfil: "Velocidad extrema y gran agilidad.",
    tags: ["Pace", "Explosive", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "rosemonde-kouassi",
    nombre: "Rosemonde Kouassi",
    ovr: null,
    posicionPrincipal: "RW",
    posiciones: ["RW", "LW"],
    categoria: "EXT",
    prioridadMeta: 3,
    perfil: "Hidden meta de muchísimo ritmo y agilidad.",
    tags: ["Hidden Meta", "Pace", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "baris-alper-yilmaz",
    nombre: "Barış Alper Yılmaz",
    ovr: null,
    posicionPrincipal: "RW",
    posiciones: ["RW", "LW", "RM", "LM", "CAM", "ST"],
    categoria: "EXT",
    prioridadMeta: 3,
    perfil: "Extremadamente versátil y rápido.",
    tags: ["Pace", "Versátil", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "christian-pulisic",
    nombre: "Christian Pulisic",
    ovr: 83,
    posicionPrincipal: "RW",
    posiciones: ["RW", "RM", "CAM", "ST"],
    categoria: "EXT",
    prioridadMeta: 2,
    perfil: "Muy ágil y flexible en posiciones ofensivas.",
    tags: ["Dribbling", "Versátil", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "lauren-hemp",
    nombre: "Lauren Hemp",
    ovr: 87,
    posicionPrincipal: "LW",
    posiciones: ["LW", "LM"],
    categoria: "EXT",
    prioridadMeta: 2,
    perfil: "Extremo de mucha velocidad y gran regate.",
    tags: ["Pace", "Dribbling", "Trade"],
    precioMercado: 4900,
    compraIdealMin: 3800,
    compraIdealMax: 4000,
    compraMaxima: 4300,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "chloe-kelly",
    nombre: "Chloé Kelly",
    ovr: 86,
    posicionPrincipal: "RW",
    posiciones: ["RW", "RM", "LM", "LW"],
    categoria: "EXT",
    prioridadMeta: 2,
    perfil: "Buen ritmo, múltiples posiciones y perfil ofensivo completo.",
    tags: ["Pace", "Versátil"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "galeno",
    nombre: "Galeno",
    ovr: 81,
    posicionPrincipal: "LW",
    posiciones: ["LW", "LM"],
    categoria: "EXT",
    prioridadMeta: 2,
    perfil: "Extremo de ritmo muy alto para su valoración.",
    tags: ["Pace", "Starter", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  // =====================================================
  // MEDIOCAMPISTAS
  // =====================================================

  {
    id: "mohammed-kudus",
    nombre: "Mohammed Kudus",
    ovr: 81,
    posicionPrincipal: "CAM",
    posiciones: ["CAM", "RW", "RM", "ST"],
    categoria: "MED",
    prioridadMeta: 3,
    perfil: "Ofensivo muy versátil con buen perfil de gameplay.",
    tags: ["Premier", "Versátil", "Trade"],
    precioMercado: 1600,
    compraIdealMin: 1000,
    compraIdealMax: 1100,
    compraMaxima: 1200,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "aurelien-tchouameni",
    nombre: "Aurélien Tchouaméni",
    ovr: null,
    posicionPrincipal: "CDM",
    posiciones: ["CDM", "CM", "CB"],
    categoria: "MED",
    prioridadMeta: 3,
    perfil: "Mediocentro defensivo muy completo y versátil.",
    tags: ["Defensive", "Physical", "Versátil"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "khephren-thuram",
    nombre: "Khéphren Thuram",
    ovr: null,
    posicionPrincipal: "CM",
    posiciones: ["CM", "CDM"],
    categoria: "MED",
    prioridadMeta: 2,
    perfil: "Alto, físico y muy fuerte como box-to-box.",
    tags: ["Physical", "Tall", "Defensive"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "konrad-laimer",
    nombre: "Konrad Laimer",
    ovr: null,
    posicionPrincipal: "CDM",
    posiciones: ["CDM", "CM", "RB", "LB"],
    categoria: "MED",
    prioridadMeta: 2,
    perfil: "Muchísima versatilidad y muy buen perfil defensivo.",
    tags: ["Versátil", "Defensive", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "amadou-onana",
    nombre: "Amadou Onana",
    ovr: 81,
    posicionPrincipal: "CDM",
    posiciones: ["CDM", "CM"],
    categoria: "MED",
    prioridadMeta: 2,
    perfil: "Mediocentro alto, físico y muy útil como stopper.",
    tags: ["Premier", "Physical", "Tall"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "morten-hjulmand",
    nombre: "Morten Hjulmand",
    ovr: null,
    posicionPrincipal: "CDM",
    posiciones: ["CDM", "CM"],
    categoria: "MED",
    prioridadMeta: 2,
    perfil: "Muy buen perfil defensivo para equipos starter.",
    tags: ["Defensive", "Starter"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "kim-little",
    nombre: "Kim Little",
    ovr: 84,
    posicionPrincipal: "CM",
    posiciones: ["CM", "CDM"],
    categoria: "MED",
    prioridadMeta: 1,
    perfil: "Excelente regate y pase para el centro del campo.",
    tags: ["Dribbling", "Passing"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "georgia-stanway",
    nombre: "Georgia Stanway",
    ovr: null,
    posicionPrincipal: "CM",
    posiciones: ["CM"],
    categoria: "MED",
    prioridadMeta: 1,
    perfil: "Centrocampista completa y equilibrada.",
    tags: ["Box to Box", "Dribbling"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "joao-felix",
    nombre: "João Félix",
    ovr: 83,
    posicionPrincipal: "CAM",
    posiciones: ["CAM", "ST", "LM", "LW"],
    categoria: "MED",
    prioridadMeta: 2,
    perfil: "Muy técnico, ágil y flexible en ataque.",
    tags: ["Dribbling", "Versátil", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "dani-olmo",
    nombre: "Dani Olmo",
    ovr: null,
    posicionPrincipal: "CAM",
    posiciones: ["CAM", "CM", "LW"],
    categoria: "MED",
    prioridadMeta: 1,
    perfil: "Jugador técnico con buen regate y creación.",
    tags: ["Dribbling", "Passing"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  // =====================================================
  // DEFENSAS
  // =====================================================

  {
    id: "andrei-ratiu",
    nombre: "Andrei Rațiu",
    ovr: 80,
    posicionPrincipal: "RB",
    posiciones: ["RB", "RM", "RW"],
    categoria: "DEF",
    prioridadMeta: 3,
    perfil: "Lateral extremadamente rápido y muy interesante para trade.",
    tags: ["Pace", "Starter", "Trade"],
    precioMercado: 2200,
    compraIdealMin: 1400,
    compraIdealMax: 1700,
    compraMaxima: 1800,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "djed-spence",
    nombre: "Djed Spence",
    ovr: 80,
    posicionPrincipal: "RB",
    posiciones: ["RB", "LB"],
    categoria: "DEF",
    prioridadMeta: 3,
    perfil: "Lateral rápido, físico y capaz de jugar por ambos lados.",
    tags: ["Pace", "Premier", "Versátil", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "jayden-oosterwolde",
    nombre: "Jayden Oosterwolde",
    ovr: 76,
    posicionPrincipal: "CB",
    posiciones: ["CB", "LB"],
    categoria: "DEF",
    prioridadMeta: 3,
    perfil: "OVR bajo pero perfil físico y velocidad muy por encima de su media.",
    tags: ["Hidden Meta", "Tall", "Pace", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "mohamed-simakan",
    nombre: "Mohamed Simakan",
    ovr: 82,
    posicionPrincipal: "CB",
    posiciones: ["CB", "RB"],
    categoria: "DEF",
    prioridadMeta: 3,
    perfil: "Central físico y versátil, también puede jugar lateral.",
    tags: ["Physical", "Versátil", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "fikayo-tomori",
    nombre: "Fikayo Tomori",
    ovr: 80,
    posicionPrincipal: "CB",
    posiciones: ["CB"],
    categoria: "DEF",
    prioridadMeta: 3,
    perfil: "Central rápido, fuerte y clásico perfil meta.",
    tags: ["Pace", "Physical", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "jorrel-hato",
    nombre: "Jorrel Hato",
    ovr: 78,
    posicionPrincipal: "CB",
    posiciones: ["CB", "LB", "CDM"],
    categoria: "DEF",
    prioridadMeta: 2,
    perfil: "Defensa muy versátil y con buen potencial starter.",
    tags: ["Premier", "Versátil", "Starter"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "wesley-fofana",
    nombre: "Wesley Fofana",
    ovr: 79,
    posicionPrincipal: "CB",
    posiciones: ["CB"],
    categoria: "DEF",
    prioridadMeta: 2,
    perfil: "Central Premier con físico y velocidad útil.",
    tags: ["Premier", "Physical", "Starter"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "castello-lukeba",
    nombre: "Castello Lukeba",
    ovr: 81,
    posicionPrincipal: "CB",
    posiciones: ["CB"],
    categoria: "DEF",
    prioridadMeta: 2,
    perfil: "Central rápido y muy usable para su valoración.",
    tags: ["Pace", "Starter", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "alvaro-carreras",
    nombre: "Álvaro Carreras",
    ovr: null,
    posicionPrincipal: "LB",
    posiciones: ["LB", "CB", "LM"],
    categoria: "DEF",
    prioridadMeta: 2,
    perfil: "Lateral alto, rápido y muy versátil.",
    tags: ["Pace", "Versátil"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "antonee-robinson",
    nombre: "Antonee Robinson",
    ovr: 80,
    posicionPrincipal: "LB",
    posiciones: ["LB"],
    categoria: "DEF",
    prioridadMeta: 2,
    perfil: "Lateral rápido y muy útil por química Premier.",
    tags: ["Premier", "Pace", "Starter"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "alphonso-davies",
    nombre: "Alphonso Davies",
    ovr: 82,
    posicionPrincipal: "LB",
    posiciones: ["LB", "LM"],
    categoria: "DEF",
    prioridadMeta: 3,
    perfil: "Uno de los laterales más rápidos y meta del lanzamiento.",
    tags: ["Pace", "Explosive", "Trade"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  // =====================================================
  // PORTEROS
  // =====================================================

  {
    id: "david-de-gea",
    nombre: "David de Gea",
    ovr: null,
    posicionPrincipal: "GK",
    posiciones: ["GK"],
    categoria: "POR",
    prioridadMeta: 1,
    perfil: "Portero alto y con buenos reflejos.",
    tags: ["GK", "Tall"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "giorgi-mamardashvili",
    nombre: "Giorgi Mamardashvili",
    ovr: null,
    posicionPrincipal: "GK",
    posiciones: ["GK"],
    categoria: "POR",
    prioridadMeta: 2,
    perfil: "Portero muy alto, interesante por alcance.",
    tags: ["GK", "Tall", "Starter"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  },

  {
    id: "bounou",
    nombre: "Bounou",
    ovr: null,
    posicionPrincipal: "GK",
    posiciones: ["GK"],
    categoria: "POR",
    prioridadMeta: 1,
    perfil: "Portero alto y fiable.",
    tags: ["GK", "Tall"],
    precioMercado: null,
    compraIdealMin: null,
    compraIdealMax: null,
    compraMaxima: null,
    ultimaActualizacion: null,
    activo: true
  }
];
